[workspace]
resolver = "3"
members = ["a-getting-start", "axum-practice", "b-guessing-game", "backyard", "c-programming-concepts", "d-ownership", "default-trait", "dyn-practice", "minigrep", "n-closure", "reqwest-practice", "tracing-practice", "understand-trait"]
